'use strict';

const colors = {
    'transparent': `transparent`,
    'dark': `#253137`,

    'black': `#22292F`,
    'grey-darkest': `#3D4852`,
    'grey-darker': `#606F7B`,
    'grey-dark': `#8795A1`,
    'grey': `#B8C2CC`,
    'grey-light': `#DAE1E7`,
    'grey-lighter': `#F1F5F8`,
    'grey-lightest': `#F8FAFC`,
    'white': `#FFFFFF`,

    'red-darkest': `#3B0D0C`,
    'red-darker': `#621B18`,
    'red-dark': `#CC1F1A`,
    'red': `#E3342F`,
    'red-light': `#EF5753`,
    'red-lighter': `#F9ACAA`,
    'red-lightest': `#FCEBEA`,

    'orange-darkest': `#462A16`,
    'orange-darker': `#613B1F`,
    'orange-dark': `#DE751F`,
    'orange': `#F6993F`,
    'orange-light': `#FAAD63`,
    'orange-lighter': `#FCD9B6`,
    'orange-lightest': `#FFF5EB`,

    'yellow-darkest': `#453411`,
    'yellow-darker': `#684F1D`,
    'yellow-dark': `#F2D024`,
    'yellow': `#FFED4A`,
    'yellow-light': `#FFF382`,
    'yellow-lighter': `#FFF9C2`,
    'yellow-lightest': `#FCFBEB`,

    'green-darkest': `#0F2F21`,
    'green-darker': `#1A4731`,
    'green-dark': `#1F9D55`,
    'green': `#38C172`,
    'green-light': `#51D88A`,
    'green-lighter': `#A2F5BF`,
    'green-lightest': `#E3FCEC`,

    'teal-darkest': `#0D3331`,
    'teal-darker': `#20504F`,
    'teal-dark': `#38A89D`,
    'teal': `#4DC0B5`,
    'teal-light': `#64D5CA`,
    'teal-lighter': `#A0F0ED`,
    'teal-lightest': `#E8FFFE`,

    'blue-darkest': `#12283A`,
    'blue-darker': `#1C3D5A`,
    'blue-dark': `#2779BD`,
    'blue': `#3490DC`,
    'blue-light': `#6CB2EB`,
    'blue-lighter': `#BCDEFA`,
    'blue-lightest': `#EFF8FF`,

    'indigo-darkest': `#191E38`,
    'indigo-darker': `#2F365F`,
    'indigo-dark': `#5661B3`,
    'indigo': `#6574CD`,
    'indigo-light': `#7886D7`,
    'indigo-lighter': `#B2B7FF`,
    'indigo-lightest': `#E6E8FF`,

    'purple-darkest': `#21183C`,
    'purple-darker': `#382B5F`,
    'purple-dark': `#794ACF`,
    'purple': `#9561E2`,
    'purple-light': `#A779E9`,
    'purple-lighter': `#D6BBFC`,
    'purple-lightest': `#F3EBFF`,

    'pink-darkest': `#451225`,
    'pink-darker': `#6F213F`,
    'pink-dark': `#EB5286`,
    'pink': `#F66D9B`,
    'pink-light': `#FA7EA8`,
    'pink-lighter': `#FFBBCA`,
    'pink-lightest': `#FFEBEF`,
};

const allColors = {
    ...colors,

    'primary': `#2B547E`,
    'secondary': `#0090FF`,
    'danger': colors.red,
    'warning': colors.orange,
    'info': `#7CADD3`,
    'success': colors.green,

};

module.exports = {

    'prefix': `tw-`,
    'important': false,
    'separator': `--`,

    'theme': {
        'colors': allColors,
        'borderColor': theme => theme('colors'),
        'borderWidth': {
            'default': `1px`,
            '0': `0`,
            '1': `1px`,
            '2': `2px`,
            '3': `3px`,
            '4': `4px`,
            '6': `6px`,
            '8': `8px`,
        },

        'fontFamily': {
            'sans': [
                'system-ui',
                'BlinkMacSystemFont',
                '-apple-system',
                'Segoe UI',
                'Roboto',
                'Oxygen',
                'Ubuntu',
                'Cantarell',
                'Fira Sans',
                'Droid Sans',
                'Helvetica Neue',
                'sans-serif',
            ],
            'serif': [
                'Constantia',
                'Lucida Bright',
                'Lucidabright',
                'Lucida Serif',
                'Lucida',
                'DejaVu Serif',
                'Bitstream Vera Serif',
                'Liberation Serif',
                'Georgia',
                'serif',
            ],
            'mono': [
                'Menlo',
                'Monaco',
                'Consolas',
                'Liberation Mono',
                'Courier New',
                'monospace',
            ]
        },
        'textColor': theme => theme('colors'),
        'width': theme => ({
            'auto': 'auto',
            ...theme('spacing'),
            '1/2': '50%',
            '1/3': '33.333333%',
            '2/3': '66.666667%',
            '1/4': '25%',
            '2/4': '50%',
            '3/4': '75%',
            '1/5': '20%',
            '2/5': '40%',
            '3/5': '60%',
            '4/5': '80%',
            '1/6': '16.666667%',
            '2/6': '33.333333%',
            '3/6': '50%',
            '4/6': '66.666667%',
            '5/6': '83.333333%',
            '1/8': '12.5%',
            '2/8': '25%',
            '3/8': '37.5%',
            '4/8': '50%',
            '5/8': '62.5%',
            '6/8': '75%',
            '7/8': '87.5%',
            '1/12': '8.333333%',
            '2/12': '16.666667%',
            '3/12': '25%',
            '4/12': '33.333333%',
            '5/12': '41.666667%',
            '6/12': '50%',
            '7/12': '58.333333%',
            '8/12': '66.666667%',
            '9/12': '75%',
            '10/12': '83.333333%',
            '11/12': '91.666667%',
            'full': '100%',
            'screen': '100vw',
        }),
    },

    'plugins': [
        require('tailwindcss/lib/plugins/container')({
            'center': true,
            'padding': '1rem',
        }),
    ],
    'variants': {
        'appearance': [ 'responsive' ],
        'backgroundAttachment': [ 'responsive' ],
        'backgroundColors': [
            'responsive',
            'hover',
            'focus',
            'active',
        ],
        'backgroundPosition': [ 'responsive' ],
        'backgroundRepeat': [ 'responsive' ],
        'backgroundSize': [ 'responsive' ],
        'borderCollapse': [],
        'borderColors': [
            'responsive',
            'hover',
            'focus',
            'active',
        ],
        'borderRadius': [ 'responsive' ],
        'borderStyle': [
            'responsive',
            'hover',
            'focus',
            'active',
        ],
        'borderWidths': [ 'responsive' ],
        'cursor': [ 'responsive' ],
        'display': [ 'responsive' ],
        'flexbox': [ 'responsive' ],
        'float': [ 'responsive' ],
        'fonts': [ 'responsive' ],
        'fontWeights': [
            'responsive',
            'hover',
            'focus'
        ],
        'height': [ 'responsive' ],
        'leading': [ 'responsive' ],
        'lists': [ 'responsive' ],
        'margin': [ 'responsive' ],
        'maxHeight': [ 'responsive' ],
        'maxWidth': [ 'responsive' ],
        'minHeight': [ 'responsive' ],
        'minWidth': [ 'responsive' ],
        'negativeMargin': [ 'responsive' ],
        'opacity': [
            'responsive',
            'focus',
            'hover',
            'active',
        ],
        'outline': [
            'focus',
            'hover',
            'active',
        ],
        'overflow': [ 'responsive' ],
        'padding': [ 'responsive' ],
        'pointerEvents': [
            'responsive',
            'hover',
            'active',
        ],
        'position': [ 'responsive' ],
        'resize': [ 'responsive' ],
        'shadows': [
            'responsive',
            'hover',
            'focus',
            'active',
        ],
        'svgFill': [],
        'svgStroke': [],
        'tableLayout': [ 'responsive' ],
        'textAlign': [ 'responsive' ],
        'textColors': [
            'responsive',
            'hover',
            'focus',
            'active',
        ],
        'textSizes': [ 'responsive' ],
        'textStyle': [
            'responsive',
            'hover',
            'focus',
            'active',
        ],
        'tracking': [ 'responsive' ],
        'userSelect': [ 'responsive' ],
        'verticalAlign': [ 'responsive' ],
        'visibility': [ 'responsive' ],
        'whitespace': [ 'responsive' ],
        'width': [ 'responsive' ],
        'zIndex': [ 'responsive' ],
    },
};
